# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: player.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='player.proto',
  package='Player',
  serialized_pb=_b('\n\x0cplayer.proto\x12\x06Player\")\n\x08PlayerIP\x12\x11\n\tplayer_no\x18\x01 \x02(\r\x12\n\n\x02IP\x18\x02 \x02(\t\"W\n\x08StartMsg\x12\x15\n\rproto_version\x18\x01 \x02(\r\x12\x11\n\tplayer_no\x18\x02 \x02(\r\x12!\n\x07players\x18\x03 \x03(\x0b\x32\x10.Player.PlayerIP\"\x81\x01\n\x07GameMsg\x12\r\n\x05mtype\x18\x01 \x02(\r\x12\x11\n\tplayer_no\x18\x02 \x02(\r\x12%\n\x03pos\x18\x03 \x01(\x0b\x32\x18.Player.GameMsg.Position\x12\x0b\n\x03\x64ir\x18\x04 \x01(\r\x1a \n\x08Position\x12\t\n\x01x\x18\x01 \x02(\x02\x12\t\n\x01y\x18\x02 \x02(\x02')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PLAYERIP = _descriptor.Descriptor(
  name='PlayerIP',
  full_name='Player.PlayerIP',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='player_no', full_name='Player.PlayerIP.player_no', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='IP', full_name='Player.PlayerIP.IP', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=65,
)


_STARTMSG = _descriptor.Descriptor(
  name='StartMsg',
  full_name='Player.StartMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='proto_version', full_name='Player.StartMsg.proto_version', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='player_no', full_name='Player.StartMsg.player_no', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='players', full_name='Player.StartMsg.players', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=154,
)


_GAMEMSG_POSITION = _descriptor.Descriptor(
  name='Position',
  full_name='Player.GameMsg.Position',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='Player.GameMsg.Position.x', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='Player.GameMsg.Position.y', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=254,
  serialized_end=286,
)

_GAMEMSG = _descriptor.Descriptor(
  name='GameMsg',
  full_name='Player.GameMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mtype', full_name='Player.GameMsg.mtype', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='player_no', full_name='Player.GameMsg.player_no', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pos', full_name='Player.GameMsg.pos', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dir', full_name='Player.GameMsg.dir', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_GAMEMSG_POSITION, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=157,
  serialized_end=286,
)

_STARTMSG.fields_by_name['players'].message_type = _PLAYERIP
_GAMEMSG_POSITION.containing_type = _GAMEMSG
_GAMEMSG.fields_by_name['pos'].message_type = _GAMEMSG_POSITION
DESCRIPTOR.message_types_by_name['PlayerIP'] = _PLAYERIP
DESCRIPTOR.message_types_by_name['StartMsg'] = _STARTMSG
DESCRIPTOR.message_types_by_name['GameMsg'] = _GAMEMSG

PlayerIP = _reflection.GeneratedProtocolMessageType('PlayerIP', (_message.Message,), dict(
  DESCRIPTOR = _PLAYERIP,
  __module__ = 'player_pb2'
  # @@protoc_insertion_point(class_scope:Player.PlayerIP)
  ))
_sym_db.RegisterMessage(PlayerIP)

StartMsg = _reflection.GeneratedProtocolMessageType('StartMsg', (_message.Message,), dict(
  DESCRIPTOR = _STARTMSG,
  __module__ = 'player_pb2'
  # @@protoc_insertion_point(class_scope:Player.StartMsg)
  ))
_sym_db.RegisterMessage(StartMsg)

GameMsg = _reflection.GeneratedProtocolMessageType('GameMsg', (_message.Message,), dict(

  Position = _reflection.GeneratedProtocolMessageType('Position', (_message.Message,), dict(
    DESCRIPTOR = _GAMEMSG_POSITION,
    __module__ = 'player_pb2'
    # @@protoc_insertion_point(class_scope:Player.GameMsg.Position)
    ))
  ,
  DESCRIPTOR = _GAMEMSG,
  __module__ = 'player_pb2'
  # @@protoc_insertion_point(class_scope:Player.GameMsg)
  ))
_sym_db.RegisterMessage(GameMsg)
_sym_db.RegisterMessage(GameMsg.Position)


# @@protoc_insertion_point(module_scope)
