# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: player.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='player.proto',
  package='Player',
  serialized_pb=_b('\n\x0cplayer.proto\x12\x06Player\")\n\x08PlayerIP\x12\x11\n\tplayer_no\x18\x01 \x02(\r\x12\n\n\x02IP\x18\x02 \x02(\t\"W\n\x08StartMsg\x12\x15\n\rproto_version\x18\x01 \x02(\r\x12\x11\n\tplayer_no\x18\x02 \x02(\r\x12!\n\x07players\x18\x03 \x03(\x0b\x32\x10.Player.PlayerIP')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PLAYERIP = _descriptor.Descriptor(
  name='PlayerIP',
  full_name='Player.PlayerIP',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='player_no', full_name='Player.PlayerIP.player_no', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='IP', full_name='Player.PlayerIP.IP', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=65,
)


_STARTMSG = _descriptor.Descriptor(
  name='StartMsg',
  full_name='Player.StartMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='proto_version', full_name='Player.StartMsg.proto_version', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='player_no', full_name='Player.StartMsg.player_no', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='players', full_name='Player.StartMsg.players', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=154,
)

_STARTMSG.fields_by_name['players'].message_type = _PLAYERIP
DESCRIPTOR.message_types_by_name['PlayerIP'] = _PLAYERIP
DESCRIPTOR.message_types_by_name['StartMsg'] = _STARTMSG

PlayerIP = _reflection.GeneratedProtocolMessageType('PlayerIP', (_message.Message,), dict(
  DESCRIPTOR = _PLAYERIP,
  __module__ = 'player_pb2'
  # @@protoc_insertion_point(class_scope:Player.PlayerIP)
  ))
_sym_db.RegisterMessage(PlayerIP)

StartMsg = _reflection.GeneratedProtocolMessageType('StartMsg', (_message.Message,), dict(
  DESCRIPTOR = _STARTMSG,
  __module__ = 'player_pb2'
  # @@protoc_insertion_point(class_scope:Player.StartMsg)
  ))
_sym_db.RegisterMessage(StartMsg)


# @@protoc_insertion_point(module_scope)
